### ISSUE TITLE
Thank You for the amazing work.

### ISSUE THREAD

**Issue by afkcodes** [SunnieShine/Sudoku#582]
Hi, Sunnie This is an amazing work that you have done, i just tried this and was blown away by the way it has been carefully done. All the very best an keep updating this project. you have done a great work. 
Are you on discord or somewhere else would love to connect with you.

**Comment by SunnieShine** [comment]
Hello. Sorry for late.

Thanks for your reply. I'm glad to hear this 😄 TBH I only use GitHub, due to troublesome reason, I don't have enough time online using other social media in normal days 😢 I'm so sorry.

**Comment by afkcodes** [comment]
No issue, i was trying to batch generate puzzles that are very easy, tried the technique count constraints, with default settings with full house selected. the file was completely polluted, and there was no puzzles.

**Comment by SunnieShine** [comment]
Full House is the simplest technique used in sudoku. All possible puzzles will use this technique. :-)

**Comment by afkcodes** [comment]
understood but when i tried to batch generate it in a file i got the puzzles like this . Have a look at this file, there is something wrong

[Very-easy.txt](https://github.com/SunnieShine/Sudoku/files/14734386/Very-easy.txt)

**Comment by SunnieShine** [comment]
Hello. From the file I cannot determine what the wrong is.

Could you please provide me your defined constraints? Have you added "Difficulty Level Constraint"? The constraint will limit the difficulty level of the puzzle to the specified one. If you don't set this, **all possible** difficulty levels will be available.

If you want to limit the technique used in solving puzzle, there is no way to do this because I use a general algorithm to achieve this. If you want to limit the puzzle using *only* Full House, I may add a new issue to add special handling on such techniques in generating.

---

I also found that the output file contains some puzzles use Hodoku extended format:

![image](https://github.com/SunnieShine/Sudoku/assets/23616315/569c7010-e0a8-480b-b5fd-5f8c2633ad23)

The text isn't mal-formatted, the rules are defined in Hodoku, and I just shrink the length of the text by removing the prefix `:0000:x:` and the final colon token `:`.

Hodoku format is like

```text
:prefix:digit:puzzle:eliminations:extra:
```

The parts "prefix" and "digit" isn't defined in my application, so I removed them.

However, some rules are still reserved. For example, the plus token `+` represents such digit is filled after the grid given. For example, `+2` means the digit 2 is not a given digit, but a digit that is filled after the puzzle having been solved with some steps making the corrsponding cell to be filled with 2.

Such tokens exist because the grid parsed from the text represents the grid is at the "current puzzle state", meaning it may be solved in some other steps.

---

From your description in this issue, I think that you may want to limit the output file only displaying for "initial grid" instead of "current grid". I'm sorry that the application may not implement for this. If I understand correctly, I can implement for it in the next version.

Thank you for your reply and patience.

**Comment by afkcodes** [comment]
![image](https://github.com/SunnieShine/Sudoku/assets/17390257/3ed16328-5680-4800-a49f-5d3669cafc08)

this was the config that i selected and modified the count. I was actually trying to make some puzzles that would only contain fullhouse and was expecting the string to be something similar to this

62.315..757..64.....3..25..1.....97593..4..82285.....3..42..7.....43..518..671.24

i understood your point and reply, thanks for being such detailed.  For me i would just love to create puzzled with only a single technique so that it would help me learn better. also i was thinking to make a small game for myself to play. 

This will be great if you can add this feature to handle these situations. 

Thank you you are amazing, and cool. :)

**Comment by SunnieShine** [comment]
Such constraints only check for validity of a puzzle that **satisfies** such rules. As for "technique count constraint" if a puzzle contains at least 4 full houses, the puzzle will be treated as a valid puzzle and output into the file. Therefore it may not not be good for your expectation.

I'll work on this in next release to limit techniques only use Full Houses or other single techniques. Thanks for your suggestion!

**Comment by afkcodes** [comment]
Thank you so much @SunnieShine  it's been so great having conversation with you. Looking forward for some amazing features going forward.

**Comment by afkcodes** [comment]
Hie @SunnieShine saw the commit for the fullhouse only puzzles, it will be a great option if we can generate other puzzles as well by selecting a specific technique. Like X-wing or others as well. but for the start this is awesome, cant wait.

**Comment by SunnieShine** [comment]
Hello. Sorry for late.

I've implemented the issue.

![](https://github.com/SunnieShine/Sudoku/assets/23616315/3d83deff-c135-4b7a-b3f2-c789fe23dbd7)

![](https://github.com/SunnieShine/Sudoku/assets/23616315/1de09e6c-2a28-44f8-98b2-4142835810a6)

---

It seems that the constraint page is too complex to be used. I will give you a simple introduction for that page.

Today we have these constraints:

![](https://github.com/SunnieShine/Sudoku/assets/23616315/ca36cec5-78da-4a1d-954b-205b4f16f5d2)

Please see this table to learn more information about such constraints:

| Constraint Name                      | Can Declare Multiple Items | Description                                                  |
| ------------------------------------ | -------------------------- | ------------------------------------------------------------ |
| Difficulty Level Constraint          | ❌                          | The constraint will control the difficulty level of a puzzle. |
| Count-between Constraint             | ❌                          | The constraint will control the number of given cells or empty cells, to make the puzzle hold the specified number of such cells. |
| Symmetry Constraint                  | ❌                          | The constraint will control the pattern symmetry of generated puzzles. Supports multiple selections. |
| Technique Constraint                 | ❌                          | The constraint will control the technique used. For the latest reply, I think this constraint will solve your problem. However, some techniques may be appeared very rare. I may not support technique-based puzzle-generating APIs, so constraints to such techniques may not behave well. |
| Technique Appearing-Times Constraint | ✅                          | The constraint will control the number of appearances of one technique. For example, if you want to make "X-Wing" contains at most 1 time, use this constraint to set control values to "(Less Than or Equals) <=" and "1". |
| Elimination Count Constraint         | ❌                          | The constraint will control the number of eliminations appeared in one step. If you want to make a puzzle contains a step with 10+ eliminations, use this constraint to set control values to "Greater Than (>)" and "10". |
| Conclusion Constraint                | ✅                          | The constraint will control the appearance for the elimination. For example, if you want to make a puzzle contains the elimination like `r5c5 <> 5`, use this constraint to set control values to "row 5, column 5, digit 5". |
| Pearl Constraint                     | ❌                          | The constraint checks whether a puzzle is a pearl puzzle, meaning steps before the first value-set step (this application calls this "an assignment step") contains the step that holds the maximum difficulty rating in all solving steps. This limits the puzzle contains at least 1 step creating eliminations, and the first step must be "an elimination step". |
| Diamond Constraint                   | ❌                          | The constraint checks whether a puzzle is a diamond puzzle, meaning the first step holds the maximum diffculty rating in all solving steps. Same as pearl puzzles, this also limits the puzzle at least 1 step creating eliminations, and the first step must be "an elimination step". |
| Minimal Constraint                   | ❌                          | The constraint checks whether a puzzle is a minimal puzzle, meaning all given digits are necessary. If we remove a digit from the puzzle, the puzzle will become an invalid puzzle that contains multiple solutions. |
| Ittoryu Constraint                   | ❌                          | The constraint checks whether a puzzle is an ittoryu puzzle. The word "ittoryu" comes from Japanese "一刀流（いっとうりゅう）". Ittoryu puzzles can be solved digit by digit in order. For example, you can firstly fill all cells with digit 1, and then all cells with digit 2, digit 3, etc. until the digit 9. After all cells filling with digit 9 are completed, the puzzle will be completed. |
| Ittoryu Length Constraint            | ❌                          | The constraint checks whether a puzzle has ittoryu trace. A puzzle may not be an ittoryu, but it can be solved with some of 9 digits based ittoryu rule. If a puzzle can complete 3 kinds of digits (e.g. digit 1, 2 and 3) one by one, the ittoryu length will be 3. If the value is 9, the puzzle will become an ittoryu. |
| Primary Single Constraint            | ❌                          | The constraints checks the assignment solving techniques. Only one technique can be used (Full House, Hidden Single or Naked Single), and checks whether the puzzle can be solved under the limitation. This rule corresponds to this issue, and extends it, because you may not always set technique Full House. |

All constraints can be mixed with the others. However, due to the complexity of such mixing, I may not implement validity checking on mixing constraints. Some constraints mixed may lead to a confliction. For example, an ittoryu puzzle must be at difficult level "Easy", so we cannot set the difficulty level constraint to "hard" or other levels not "easy".

**Comment by afkcodes** [comment]
wow this is so comprehensive, i will read them and try to understand. Thank you :)
